# Create directory if needed
New-Item -ItemType Directory -Force -Path .github/workflows

# Create workflow file
@'
name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov

    - name: Run tests
      run: |
        pytest tests/ -v --cov=app --cov=core

    - name: Check code quality
      run: |
        pip install flake8
        flake8 app core --max-line-length=120 --exclude=__pycache__

  build:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker build -t credify:${{ github.sha }} .
        docker build -t credify:latest .

    - name: Test Docker image
      run: |
        docker run -d -p 5000:5000 --name test-app credify:latest
        sleep 10
        curl -f http://localhost:5000/ || exit 1
        docker stop test-app

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Deploy to Render
      run: |
        echo "🚀 Render will auto-deploy from main branch"
        echo "✅ Check https://dashboard.render.com"
'@ | Out-File -FilePath .github/workflows/ci.yml -Encoding UTF8
